---
:ems:
  :ems_lenovo:
    :blacklisted_event_names: []
    :event_handling:
      :connection_timeout: 90
      :events_pool_percentage: 0.07
      :event_groups:
        :power:
          :critical:
          - 'CMM0157'
          - 'FQXHMDM0125I'
          :detail:
          - 'PLAT0107'
          - 'PLAT0106'
          - 'IMM0130'
          - 'IMM0125'
          - 'IMM0186'
          - 'IMM0131'
          - 'IMM0177'
          - 'PLAT0286'
          - 'IMM0180'
          - 'IMM0166'
          - 'IMM0174'
          - 'IMM0175'
          - 'IMM0210'
          - 'IMM0169'
          - 'IMM0168'
          - 'IMM0127'
          - 'IMM0185'
          - 'IMM0170'
          - 'PLAT0108'
          - 'IMM0171'
          - 'IMM0178'
          - 'IMM0176'
          - 'IMM0181'
          - 'IMM0184'
          :warning:
          - 'IMM0117'
          - 'IMM0118'
          :name: Power Activity
        :firmware:
          :critical:
          - '806F072B2201FFFF'
          - '000AB001'
          - '000AB002'
          - '000AB003'
          - '000AB004'
          - '000AB005'
          - '000AB006'
          - '000AB007'
          - '000AB008'
          - '000AB009'
          - '00015105'
          - '0EA02101'
          - '0EA02102'
          - '0EA02103'
          - '0EA02104'
          - '00015101'
          - 'FQXHMUP4007I'
          - '00017310'
          - '00017129'
          - '00015103'
          - '806F072B2101FFFF'
          - '806F072B2201FFFF'
          - 'FQXHMUP4006I'
          - 'FQXHMUP4007I'
          - 'FQXHMUP4008I'
          - 'IMM0132'
          - 'IMM0042'
          - 'PLAT0186'
          - 'IMM0031'
          - 'IMM0133'
          :detail:
          - 'PLAT0187'
          :warning: []
          :name: Firmware
        :devices:
          :critical:
          - 'CMM0100'
          - 'PLAT0162'
          - 'PLAT0456'
          - 'CMM0101'
          - 'PLAT0457'
          - 'CMM0102'
          - '806F000D0401FFFF'
          - '806F000D0402FFFF'
          - '806F000D0403FFFF'
          - '806F000D0404FFFF'
          - '806F000D0405FFFF'
          - '806F000D0406FFFF'
          - '806F000D0407FFFF'
          - '816F000D0400FFFF'
          - '816F000D0401FFFF'
          - '816F000D0402FFFF'
          - '816F000D0403FFFF'
          - '816F000D0404FFFF'
          - '816F000D0405FFFF'
          - '816F000D0406FFFF'
          - '816F000D0407FFFF'
          - 'PLAT0530'
          - 'PLAT0802'
          - 'PLAT0524'
          - 'PLAT0494'
          - 'PLAT0480'
          - 'PLAT0810'
          - 'PLAT0522'
          - 'PLAT0498'
          :detail:
          - 'PLAT0477'
          - 'PLAT0508'
          - 'PLAT0811'
          - 'PLAT0803'
          - 'PLAT0509'
          - 'PLAT0495'
          - 'PLAT0399'
          - 'PLAT0521'
          - 'PLAT0518'
          - 'PLAT0491'
          - 'PLAT0523'
          - 'PLAT0531'
          - 'PLAT0481'
          - 'PLAT0525'
          - 'PLAT0499'
          :warning:
          - 'IMM0142'
          - 'PLAT0476'
          - 'PLAT0398'
          - 'PLAT0490'
          - 'PLAT0520'
          :name: Devices
        :network:
          :critical: []
          :detail:
          - 'IMM0056'
          - 'IMM0025'
          - 'IMM0107'
          - 'IMM0055'
          - 'IMM0159'
          - 'IMM0024'
          - 'IMM0022'
          - 'IMM0160'
          - 'IMM0001'
          - 'IMM0023'
          - 'IMM0057'
          :warning:
          - 'IMM0013'
          - 'IMM0059'
          :name: Network
        :login:
          :critical: []
          :detail:
          - 'IMM0014'
          - 'IMM0154'
          - 'IMM0156'
          - 'IMM0153'
          - 'IMM0140'
          - 'IMM0157'
          - 'IMM0155'
          - 'IMM0158'
          - 'IMM0041'
          - 'IMM0102'
          :warning:
          - 'IMM0016'
          - 'IMM0017'
          :name: Login
        :security:
          :detail:
          - 'IMM0206'
          - 'IMM0151'
          - 'PLAT0536'
          - 'IMM0207'
          - 'PLAT0392'
          - 'PLAT0390'
          - 'IMM0204'
          - 'IMM0165'
          - 'IMM0150'
          - 'IMM0208'
          - 'PLAT0450'
          - 'IMM0205'
          :critical:
          - 'PLAT0794'
          - 'IMM0002'
          - 'PLAT0850'
          - 'PLAT0146'
          - 'PLAT0050'
          - 'PLAT0036'
          - 'IMM0034'
          - 'PLAT0446'
          :warning: []
          :name: Security
        :status:
          :detail:
          - 'IMM0097'
          - 'IMM0068'
          - 'IMM0052'
          - 'IMM0061'
          - 'IMM0194'
          - 'IMM0123'
          - 'IMM0113'
          - 'IMM0134'
          - 'IMM0101'
          - 'IMM0098'
          - 'IMM0195'
          - 'PLAT0167'
          - 'IMM0026'
          - 'IMM0163'
          - 'IMM0116'
          - 'IMM0091'
          - 'IMM0082'
          - 'IMM0033'
          - 'IMM0086'
          - 'PLAT0085'
          - 'IMM0040'
          - 'IMM0090'
          - 'IMM0069'
          - 'IMM0071'
          - 'IMM0179'
          - 'IMM0064'
          - 'IMM0007'
          - 'IMM0011'
          - 'IMM0008'
          - 'PLAT0370'
          - 'IMM0049'
          - 'IMM0099'
          - 'IMM0050'
          - 'IMM0019'
          - 'IMM0203'
          - 'IMM0006'
          - 'IMM0128'
          - 'IMM0021'
          - 'IMM0121'
          - 'IMM0036'
          - 'IMM0085'
          - 'IMM0103'
          - 'IMM0003'
          - 'IMM0080'
          - 'PLAT0130'
          - 'IMM0197'
          - 'IMM0129'
          - 'IMM0191'
          - 'IMM0070'
          - 'PLAT0061'
          - 'IMM0076'
          - 'IMM0020'
          - 'IMM0190'
          - 'IMM0146'
          - 'IMM0173'
          - 'IMM0081'
          - 'PLAT0185'
          - 'PLAT0817'
          - 'IMM0112'
          - 'IMM0215'
          - 'IMM0201'
          - 'IMM0009'
          - 'IMM0035'
          - 'IMM0187'
          - 'IMM0122'
          - 'IMM0089'
          - 'IMM0152'
          - 'IMM0164'
          - 'IMM0043'
          - 'IMM0148'
          - 'IMM0053'
          - 'IMM0010'
          - 'IMM0058'
          - 'IMM0078'
          - 'IMM0167'
          - 'IMM0048'
          - 'PLAT0267'
          - 'IMM0092'
          - 'IMM0115'
          - 'IMM0004'
          - 'PLAT0374'
          - 'IMM0124'
          - 'IMM0149'
          - 'PLAT0171'
          - 'IMM0202'
          - 'IMM0044'
          - 'IMM0083'
          - 'IMM0084'
          - 'IMM0051'
          - 'IMM0143'
          - 'IMM0145'
          - 'PLAT0060'
          - 'IMM0087'
          - 'IMM0136'
          - 'IMM0093'
          - 'IMM0054'
          - 'IMM0032'
          - 'IMM0088'
          - 'IMM0027'
          - 'IMM0077'
          - 'PLAT0037'
          - 'IMM0209'
          - 'IMM0109'
          - 'IMM0183'
          - 'IMM0072'
          - 'IMM0114'
          - 'IMM0110'
          - 'IMM0214'
          - 'IMM0094'
          - 'IMM0108'
          - 'IMM0047'
          - 'IMM0135'
          - 'IMM0141'
          - 'IMM0062'
          - 'IMM0074'
          - 'IMM0212'
          - 'IMM0119'
          - 'PLAT0145'
          - 'IMM0189'
          - 'IMM0120'
          - 'IMM0111'
          - 'PLAT0179'
          - 'IMM0199'
          - 'IMM0065'
          - 'IMM0073'
          - 'PLAT0331'
          - 'PLAT0139'
          - 'IMM0075'
          - 'IMM0015'
          - 'IMM0172'
          - 'IMM0018'
          - 'PLAT0170'
          - 'IMM0147'
          - 'IMM0066'
          - 'IMM0067'
          - 'IMM0182'
          - 'IMM0188'
          - 'IMM0045'
          - 'IMM0095'
          - 'IMM0139'
          - 'PLAT0372'
          - 'IMM0079'
          - 'IMM0063'
          - 'IMM0005'
          - 'IMM0198'
          - 'IMM0196'
          - 'PLAT0163'
          - 'PLAT0147'
          - 'IMM0144'
          - 'PLAT0131'
          - 'PLAT0127'
          - 'IMM0211'
          :critical:
          - 'PLAT0138'
          - 'IMM0137'
          - 'PLAT0770'
          - 'PLAT0164'
          - 'IMM0029'
          - 'PLAT0086'
          - 'PLAT0044'
          - 'PLAT0244'
          - 'PLAT0764'
          - 'PLAT0176'
          - 'PLAT0816'
          - 'PLAT0042'
          - 'IMM0138'
          - 'PLAT0766'
          - 'PLAT0240'
          - 'PLAT0126'
          :warning:
          - 'IMM0012'
          :name: Status
        :addition:
          :critical: []
          :detail:
          - 'IMM0106'
          - 'PLAT0084'
          - 'IMM0100'
          - 'IMM0096'
          :warning: []
          :name: Creation/Addition
:ems_refresh:
  :lenovo_ph_infra:
    :inventory_collections:
      :saver_strategy: default
:http_proxy:
  :lenovo:
    :host:
    :password:
    :port:
    :user:
:log:
  :level_lenovo: info
:workers:
  :ems_refresh_worker_lenovo_physical_infra:
    :inherits_from: ems_refresh_worker
  :event_catcher_lenovo:
    :inherits_from: event_catcher
    :poll: 15.seconds
